openapi: 3.0.1
info:
  title: Element API
  description: API for managing elements asynchronously
  version: 1.0.0
paths:
  /api/elements:
    post:
      summary: Save elements asynchronously
      description: Accepts a list of elements, processes them asynchronously, and returns a success message immediately.
      operationId: saveElements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Element'
      responses:
        '200':
          description: Elements are being saved asynchronously
          content:
            application/json:
              schema:
                type: string
                example: "Elements are being saved asynchronously"
        '400':
          description: Invalid data in request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                  path:
                    type: string
                  status:
                    type: integer
                  error:
                    type: string
                  requestId:
                    type: string
components:
  schemas:
    Element:
      type: object
      required:
        - id
        - name
        - value
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          minLength: 1
        value:
          type: integer
          minimum: 1